import type { NextPage } from "next";
import Head from "next/head";
const AdminPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Admin Page</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col p-4">
        <h1 className="mb-4 text-3xl">Admin Page</h1>

        <section className="flex gap-8"></section>
      </main>
    </>
  );
};

export default AdminPage;
